### ISSUE TITLE
How to get all events? 

### ISSUE THREAD

**Issue by megastef** [mattpodwysocki/win-getevent#1]
I've tried several providers and got no logs. I assume I should listen to all providers. 
Could you make 'all' as default?

**Comment by megastef** [comment]
Finally I managed to generate logs to test my app. 
```
new-eventlog -source TestApp -logname Application -MessageResourceFile C:\Test\TestApp.dll
write-eventlog -logname Application -source TestApp -eventID 3001 -entrytype Information -mess
age "Something happened." -category 1 -rawdata 10,20```

**Comment by mattpodwysocki** [comment]
@megastef I would be open to making `all` as default.  Send a PR
